spring.data.mongodb.uri=mongodb://dharshinibala001_db_user:GVbrMaW0C916JsEJ@ac-54kibvy-shard-00-00.zksez7g.mongodb.net:27017,ac-54kibvy-shard-00-01.zksez7g.mongodb.net:27017,ac-54kibvy-shard-00-02.zksez7g.mongodb.net:27017/habitflow?ssl=true&replicaSet=atlas-k0dieh-shard-0&authSource=admin
server.port=5000
spring.application.name=habitflow
