spring.data.mongodb.uri=mongodb+srv://dharshinibala001_db_user:GVbrMaW0C916JsEJ@cluster0.zksez7g.mongodb.net/habitflow?appName=Cluster0&connectTimeoutMS=30000&socketTimeoutMS=30000&serverSelectionTimeoutMS=30000
server.port=5000
spring.application.name=habitflow
